// Pure-JS build for the Admin Panel SPA — no native bundler (this machine blocks
// native binaries). Babel (pure JS) strips JSX from the concatenated template, and we
// prepend the production React UMD so the result is one self-contained, CDN-free asset:
//   resources/dist/rebel-admin.js   (React + ReactDOM + the panel app)
//   resources/dist/rebel-admin.css  (the two template stylesheets)
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const Babel = require('@babel/standalone');

const root = new URL('.', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1');
const p = (rel) => root + rel;

// 1) The app source: the concatenated template with ESM/import scaffolding stripped,
//    so React/ReactDOM resolve to the UMD globals we prepend.
const raw = readFileSync(p('resources/js/panel/main.jsx'), 'utf8');
const appSrc = raw
  .split(/\r?\n/)
  .filter((line) => !/^\s*import\s/.test(line) && !/^\s*window\.(React|ReactDOM)\s*=/.test(line))
  .join('\n');

const { code } = Babel.transform(appSrc, {
  presets: [['react', { runtime: 'classic' }]],
  filename: 'rebel-admin.jsx',
  compact: false,
});

const reactUmd = readFileSync(p('node_modules/react/umd/react.production.min.js'), 'utf8');
const reactDomUmd = readFileSync(p('node_modules/react-dom/umd/react-dom.production.min.js'), 'utf8');

mkdirSync(p('resources/dist'), { recursive: true });
writeFileSync(
  p('resources/dist/rebel-admin.js'),
  `/* Laravel Rebel Admin Panel — bundled (React ${require('react/package.json').version} + app). Generated by build.mjs. */\n` +
    reactUmd + '\n' + reactDomUmd + '\n' + code,
);

// 2) CSS: concatenate the two template stylesheets.
const css =
  readFileSync(p('resources/js/panel/styles.css'), 'utf8') + '\n' +
  readFileSync(p('resources/js/panel/styles-components.css'), 'utf8');
writeFileSync(p('resources/dist/rebel-admin.css'), css);

console.log('Built rebel-admin.js (' +
  Math.round(readFileSync(p('resources/dist/rebel-admin.js')).length / 1024) + ' KB) + rebel-admin.css (' +
  Math.round(css.length / 1024) + ' KB)');
